FROM golang:1.24.3-alpine

RUN apk add --no-cache git ca-certificates tzdata

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go mod tidy

CMD ["go", "run", "cmd/migrate/main.go"]
