// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/keywords": {
            "get": {
                "description": "Get list of keywords for a specific site",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keywords"
                ],
                "summary": "Get keywords by site",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Site ID",
                        "name": "site_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.KeywordResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new keyword for tracking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keywords"
                ],
                "summary": "Create a new keyword",
                "parameters": [
                    {
                        "description": "Keyword data",
                        "name": "keyword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateKeywordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.KeywordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/keywords/{id}": {
            "delete": {
                "description": "Delete a keyword and all its tracking data",
                "tags": [
                    "keywords"
                ],
                "summary": "Delete a keyword",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Keyword ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteKeywordResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/combined": {
            "get": {
                "description": "Get combined positions data from Google/Yandex and Wordstat sources with pagination support",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Get combined positions with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Site ID",
                        "name": "site_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "google",
                            "yandex"
                        ],
                        "type": "string",
                        "description": "Source filter (optional) - google or yandex",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include Wordstat data (optional) - true or false",
                        "name": "wordstat",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date filter (optional) - YYYY-MM-DD format",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (optional) - YYYY-MM-DD format",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 50, max: 100)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CombinedPositionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/history": {
            "get": {
                "description": "Get positions history for specific site and optional keyword with pagination support",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Get positions history with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Site ID",
                        "name": "site_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Keyword ID (optional)",
                        "name": "keyword_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "google",
                            "yandex",
                            "wordstat"
                        ],
                        "type": "string",
                        "description": "Source filter (optional) - google, yandex or wordstat",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date filter (optional) - YYYY-MM-DD format",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date filter (optional) - YYYY-MM-DD format",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Get only latest data for each keyword (optional) - true or false",
                        "name": "last",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 50, max: 100)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PositionHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/latest": {
            "get": {
                "description": "Get latest positions for all sites and keywords",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Get latest positions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.PositionResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/statistics": {
            "post": {
                "description": "Get position statistics for specific site and source within date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Get position statistics",
                "parameters": [
                    {
                        "description": "Statistics parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PositionStatisticsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PositionStatisticsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/track-google": {
            "post": {
                "description": "Track Google positions for specific site and its keywords. Can include subdomains in search.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Track Google positions for specific site",
                "parameters": [
                    {
                        "description": "Google tracking parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TrackGooglePositionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TrackPositionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/track-wordstat": {
            "post": {
                "description": "Track Wordstat positions for specific site and its keywords.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Track Wordstat positions for specific site",
                "parameters": [
                    {
                        "description": "Wordstat tracking parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TrackWordstatPositionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TrackPositionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/positions/track-yandex": {
            "post": {
                "description": "Track Yandex positions for specific site and its keywords. Can include subdomains in search.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Track Yandex positions for specific site",
                "parameters": [
                    {
                        "description": "Yandex tracking parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TrackYandexPositionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TrackPositionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sites": {
            "get": {
                "description": "Get list of tracked sites. If ids parameter is provided, returns only sites with specified IDs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Get sites",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of site IDs to filter by",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SiteResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new site for tracking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Create a new site",
                "parameters": [
                    {
                        "description": "Site data",
                        "name": "site",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SiteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sites/{id}": {
            "delete": {
                "description": "Delete a site and all its tracking data",
                "tags": [
                    "sites"
                ],
                "summary": "Delete a site",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Site ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteSiteResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CombinedPositionItem": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keyword": {
                    "type": "string"
                },
                "keyword_id": {
                    "type": "integer"
                },
                "positions": {
                    "description": "Позиции из Google/Yandex - массив позиций",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PositionData"
                    }
                },
                "site_id": {
                    "type": "integer"
                },
                "wordstat": {
                    "description": "Wordstat позиции - отдельный ключ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.PositionData"
                        }
                    ]
                }
            }
        },
        "dto.CombinedPositionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CombinedPositionItem"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.MetaInfo"
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationInfo"
                }
            }
        },
        "dto.CreateKeywordRequest": {
            "type": "object",
            "required": [
                "site_id",
                "value"
            ],
            "properties": {
                "site_id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.CreateSiteRequest": {
            "type": "object",
            "required": [
                "domain"
            ],
            "properties": {
                "domain": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteKeywordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteSiteResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.KeywordResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "site_id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.MetaInfo": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean"
                },
                "query_time_ms": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginationInfo": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "from": {
                    "type": "integer"
                },
                "has_more": {
                    "type": "boolean"
                },
                "last_page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "to": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.PositionData": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "dto.PositionDistribution": {
            "type": "object",
            "properties": {
                "not_found": {
                    "type": "integer"
                },
                "top_10": {
                    "type": "integer"
                },
                "top_20": {
                    "type": "integer"
                },
                "top_3": {
                    "type": "integer"
                }
            }
        },
        "dto.PositionHistoryItem": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keyword": {
                    "type": "string"
                },
                "keyword_id": {
                    "type": "integer"
                },
                "lang": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "site_id": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "dto.PositionHistoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PositionHistoryItem"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.MetaInfo"
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationInfo"
                }
            }
        },
        "dto.PositionRanges": {
            "type": "object",
            "properties": {
                "100_plus": {
                    "type": "integer"
                },
                "11_30": {
                    "type": "integer"
                },
                "1_3": {
                    "type": "integer"
                },
                "31_50": {
                    "type": "integer"
                },
                "4_10": {
                    "type": "integer"
                },
                "51_100": {
                    "type": "integer"
                }
            }
        },
        "dto.PositionResponse": {
            "type": "object",
            "properties": {
                "ads": {
                    "type": "boolean"
                },
                "country": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keyword": {
                    "type": "string"
                },
                "keyword_id": {
                    "type": "integer"
                },
                "lang": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "site": {
                    "type": "string"
                },
                "site_id": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.PositionStatisticsRequest": {
            "type": "object",
            "required": [
                "date_from",
                "date_to",
                "site_id",
                "source"
            ],
            "properties": {
                "date_from": {
                    "type": "string"
                },
                "date_to": {
                    "type": "string"
                },
                "site_id": {
                    "type": "integer"
                },
                "source": {
                    "type": "string",
                    "enum": [
                        "google",
                        "yandex",
                        "wordstat"
                    ]
                }
            }
        },
        "dto.PositionStatisticsResponse": {
            "type": "object",
            "properties": {
                "keywords_count": {
                    "type": "integer"
                },
                "not_visible": {
                    "type": "integer"
                },
                "position_distribution": {
                    "$ref": "#/definitions/dto.PositionDistribution"
                },
                "position_ranges": {
                    "$ref": "#/definitions/dto.PositionRanges"
                },
                "total_positions": {
                    "type": "integer"
                },
                "trends": {
                    "$ref": "#/definitions/dto.Trends"
                },
                "visibility_stats": {
                    "$ref": "#/definitions/dto.VisibilityStats"
                },
                "visible": {
                    "type": "integer"
                }
            }
        },
        "dto.SiteResponse": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keywords_count": {
                    "type": "integer"
                }
            }
        },
        "dto.TrackGooglePositionsRequest": {
            "type": "object",
            "required": [
                "site_id"
            ],
            "properties": {
                "ads": {
                    "type": "boolean"
                },
                "ai": {
                    "description": "Парсинг блока \"Обзор от ИИ\": 0 или 1",
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                },
                "device": {
                    "type": "string",
                    "enum": [
                        "desktop",
                        "tablet",
                        "mobile"
                    ]
                },
                "filter": {
                    "description": "Скрывать похожие результаты: 0 или 1",
                    "type": "integer"
                },
                "highlights": {
                    "description": "Подсветка ключевых слов: 0 или 1",
                    "type": "integer"
                },
                "lang": {
                    "type": "string"
                },
                "loc": {
                    "description": "ID местоположения",
                    "type": "integer"
                },
                "nfpr": {
                    "description": "Отменить исправление запроса: 0 или 1",
                    "type": "integer"
                },
                "os": {
                    "type": "string",
                    "enum": [
                        "ios",
                        "android"
                    ]
                },
                "pages": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1
                },
                "raw": {
                    "description": "Полный HTML код страницы: \"page\"",
                    "type": "string"
                },
                "site_id": {
                    "type": "integer"
                },
                "subdomains": {
                    "type": "boolean"
                },
                "tbs": {
                    "description": "Google-specific parameters",
                    "type": "string"
                },
                "xml_api_key": {
                    "type": "string"
                },
                "xml_base_url": {
                    "type": "string"
                },
                "xml_user_id": {
                    "type": "string"
                }
            }
        },
        "dto.TrackPositionsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.TrackWordstatPositionsRequest": {
            "type": "object",
            "required": [
                "site_id"
            ],
            "properties": {
                "regions": {
                    "description": "ID региона Яндекса, nullable",
                    "type": "integer"
                },
                "site_id": {
                    "type": "integer"
                },
                "xml_api_key": {
                    "type": "string"
                },
                "xml_base_url": {
                    "type": "string"
                },
                "xml_user_id": {
                    "type": "string"
                }
            }
        },
        "dto.TrackYandexPositionsRequest": {
            "type": "object",
            "required": [
                "site_id"
            ],
            "properties": {
                "ads": {
                    "type": "boolean"
                },
                "country": {
                    "type": "string"
                },
                "device": {
                    "type": "string",
                    "enum": [
                        "desktop",
                        "tablet",
                        "mobile"
                    ]
                },
                "filter": {
                    "description": "Скрывать похожие результаты: 0 или 1",
                    "type": "integer"
                },
                "groupby": {
                    "description": "Yandex-specific parameters",
                    "type": "integer"
                },
                "highlights": {
                    "description": "Подсветка ключевых слов: 0 или 1",
                    "type": "integer"
                },
                "inindex": {
                    "description": "Проверка индексации: 0 или 1",
                    "type": "integer"
                },
                "lang": {
                    "type": "string"
                },
                "lr": {
                    "description": "ID региона Яндекса",
                    "type": "integer"
                },
                "os": {
                    "type": "string",
                    "enum": [
                        "ios",
                        "android"
                    ]
                },
                "pages": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1
                },
                "raw": {
                    "description": "Полный HTML код страницы: \"page\"",
                    "type": "string"
                },
                "site_id": {
                    "type": "integer"
                },
                "strict": {
                    "description": "Режим строгого соответствия: 0 или 1",
                    "type": "integer"
                },
                "subdomains": {
                    "type": "boolean"
                },
                "within": {
                    "description": "Фильтр по периоду: 77, 1, 2, 0",
                    "type": "integer"
                },
                "xml_api_key": {
                    "type": "string"
                },
                "xml_base_url": {
                    "type": "string"
                },
                "xml_user_id": {
                    "type": "string"
                }
            }
        },
        "dto.Trends": {
            "type": "object",
            "properties": {
                "declined": {
                    "type": "integer"
                },
                "improved": {
                    "type": "integer"
                },
                "stable": {
                    "type": "integer"
                }
            }
        },
        "dto.VisibilityStats": {
            "type": "object",
            "properties": {
                "avg_position": {
                    "type": "number"
                },
                "best_position": {
                    "type": "integer"
                },
                "median_position": {
                    "type": "integer"
                },
                "worst_position": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8087",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go SEO API",
	Description:      "API для отслеживания позиций сайтов в поисковых системах",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
